spring :
  datasource :
#    platform : mysql
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8
    username : jangyunyoung
    password : 9510
#    initialization-mode: never

server :
  port : 9090


firebase :
  configuration-path : firebase/notificationreceiver-service-key.json

  project-id : notificationreceiver-2bcff

logging:
  config: "classpath:logback-spring.xml"

mybatis:
  mapper-location: mapper/*.xml
